# Generated by Django 5.0.7 on 2024-07-11 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='orderhistory',
            new_name='order_history',
        ),
    ]
